/**
 * Created by ´óÈð on 2017/1/13.
 */
function config($stateProvider,$urlRouterProvider){
    $urlRouterProvider.otherwise('index')
    $stateProvider
        .state('index',{
            url:'/index',
            templateUrl:'views/index.html'
        })
        .state('login',{
            url:'/login',
            templateUrl:'views/login.html'
        })
        .state('register',{
            url:'/register',
            templateUrl:'views/register.html'
        })
        .state('msg',{
            url:'/msg',
            templateUrl:'views/msg.html'
        })
        .state('photo',{
            url:'/photo',
            templateUrl:'views/photo.html'
        })
        .state('info',{
            url:'/info',
            templateUrl:'views/info.html'
        })
        .state('scal',{
            url:'/scal',
            templateUrl:'views/scal.html'
        })
        .state('scal_mark',{
            url:'/scal_mark',
            templateUrl:'views/scal_mark.html'
        })
        .state('scal_all',{
            url:'/scal_all',
            templateUrl:'views/scal_all.html'
        })
        .state('shop',{
            url:'/shop',
            templateUrl:'views/shop.html'
        })
        .state('shop_list',{
            url:'/shop_list',
            templateUrl:'views/shop_list.html'
        })
        .state('shop_add',{
            url:'/shop_add',
            templateUrl:'views/shop_add.html'
        })
        .state('news',{
            url:'/news',
            templateUrl:'views/news.html'
        })
}
angular.module('myApp')
    .config(config);